# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190207_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='bookingfeeprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='bookingfeeprice_currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='commissionprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='commissionprice_currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='grossprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='grossprice_currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='netprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='netprice_currency',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sessionId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='settlementprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='settlementprice_currency',
        ),
        migrations.RemoveField(
            model_name='cartproductdetails',
            name='netprice',
        ),
        migrations.RemoveField(
            model_name='cartproductdetails',
            name='netprice_currency',
        ),
        migrations.RemoveField(
            model_name='cartproductdetails',
            name='passengers_num',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='commissionprice_currency',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='grossprice_currency',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='netprice_currency',
        ),
        migrations.RemoveField(
            model_name='cartproducts',
            name='settlementprice_currency',
        ),
        migrations.AddField(
            model_name='cart',
            name='deliveryaddr1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='deliveryaddr2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='deliverycity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='deliverystate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='deliveryzip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='orderid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cartproductdetails',
            name='service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cartproductpassengers',
            name='residencecountry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='agent_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='booking_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='currency_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='from_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='from_station',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='to_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='to_station',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='train',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductdetails',
            name='train_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductpassengers',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductpassengers',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductpassengers',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductpassengers',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductpassengers',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartproductpassengers',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='Rule',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='commissionprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='fare',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='grossprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='netprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='passengers_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='settlementprice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='validity',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
